data<-read.table("household_power_consumption.txt",sep=";",header=TRUE)
plot3<-filter(data,Date=="1/2/2007" | Date=="2/2/2007")
plot3$Date<-as.Date(as.character(plot3$Date),"%d/%m/%Y")
plot3$Time<-strptime(paste(plot3$Date,as.character(plot3$Time)),format= "%Y-%m-%d %H:%M:%S")
plot3$Global_active_power<-as.numeric(as.character(plot3$Global_active_power))
png(filename = "Plot3.png", width = 480, height = 480)
plot(x = plot3$Time, y = plot3$Sub_metering_1, type = "l", xlab = "", ylab = "Energy sub metering")
lines(x = plot3$Time, y = plot3$Sub_metering_2, type = "l", col = "red")
lines(x = plot3$Time, y = plot3$Sub_metering_3, type = "l", col = "blue")
legend("topright", lty = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()